package com.example.store.enums;

/** Stable, client-facing API messages. Keep technical details in logs. */
public enum ApiMessage {
    PRODUCT_LIST_SUCCESS("Products retrieved successfully."),
    PRODUCT_DETAIL_SUCCESS("Product details retrieved successfully."),
    PRODUCT_CREATE_SUCCESS("Product created successfully."),
    PRODUCT_UPDATE_SUCCESS("Product updated successfully."),
    PRODUCT_DELETE_SUCCESS("Product deleted successfully."),
    PRODUCT_RESTORE_SUCCESS("Product restored successfully."),
    PRODUCT_VARIANT_LIST_SUCCESS("Product variants retrieved successfully."),
    PRODUCT_VARIANT_PAGE_SUCCESS("Product variant page retrieved successfully."),
    PRODUCT_VARIANT_DETAIL_SUCCESS("Product variant details retrieved successfully."),
    PRODUCT_VARIANT_CREATE_SUCCESS("Product variant created successfully."),
    PRODUCT_VARIANT_UPDATE_SUCCESS("Product variant updated successfully."),
    PRODUCT_VARIANT_DELETE_SUCCESS("Product variant deleted successfully."),
    PRODUCT_VARIANT_RESTORE_SUCCESS("Product variant restored successfully."),
    PRODUCT_IMAGE_LIST_SUCCESS("Product images retrieved successfully."),
    PRODUCT_IMAGE_UPLOAD_SUCCESS("Product images uploaded successfully."),
    PRODUCT_IMAGE_DELETE_SUCCESS("Product image deleted successfully."),
    CATEGORY_LIST_SUCCESS("Categories retrieved successfully."),
    CATEGORY_OPTIONS_SUCCESS("Category options retrieved successfully."),
    CATEGORY_DETAIL_SUCCESS("Category details retrieved successfully."),
    CATEGORY_CREATE_SUCCESS("Category created successfully."),
    CATEGORY_UPDATE_SUCCESS("Category updated successfully."),
    CATEGORY_DELETE_SUCCESS("Category deleted successfully."),
    CATEGORY_RESTORE_SUCCESS("Category restored successfully."),
    BRAND_LIST_SUCCESS("Brands retrieved successfully."),
    BRAND_OPTIONS_SUCCESS("Brand options retrieved successfully."),
    BRAND_DETAIL_SUCCESS("Brand details retrieved successfully."),
    BRAND_CREATE_SUCCESS("Brand created successfully."),
    BRAND_UPDATE_SUCCESS("Brand updated successfully."),
    BRAND_DELETE_SUCCESS("Brand deleted successfully."),
    BRAND_RESTORE_SUCCESS("Brand restored successfully."),
    STYLE_LIST_SUCCESS("Styles retrieved successfully."),
    STYLE_OPTIONS_SUCCESS("Style options retrieved successfully."),
    STYLE_BY_CATEGORY_SUCCESS("Styles for the category retrieved successfully."),
    STYLE_DETAIL_SUCCESS("Style details retrieved successfully."),
    STYLE_CREATE_SUCCESS("Style created successfully."),
    STYLE_UPDATE_SUCCESS("Style updated successfully."),
    STYLE_DELETE_SUCCESS("Style deleted successfully."),
    STYLE_RESTORE_SUCCESS("Style restored successfully."),
    STYLE_VALUE_LIST_SUCCESS("Style values retrieved successfully."),
    STYLE_VALUE_OPTIONS_SUCCESS("Style value options retrieved successfully."),
    STYLE_VALUE_DETAIL_SUCCESS("Style value details retrieved successfully."),
    STYLE_VALUE_CREATE_SUCCESS("Style value created successfully."),
    STYLE_VALUE_UPDATE_SUCCESS("Style value updated successfully."),
    STYLE_VALUE_DELETE_SUCCESS("Style value deleted successfully."),
    STYLE_VALUE_RESTORE_SUCCESS("Style value restored successfully."),
    AUTH_LOGIN_SUCCESS("Login successful."),
    AUTH_LOGIN_REQUIRED("Please log in to change your password."),
    AUTH_REGISTER_SUCCESS("Registration successful. Enter the verification code sent to your email."),
    AUTH_OTP_SENT("A verification code has been sent to your email."),
    AUTH_OTP_RESENT("A new verification code has been sent to your email. It is valid for 5 minutes."),
    AUTH_ACCOUNT_ACTIVATED("Account activated successfully. You can now sign in."),
    AUTH_PASSWORD_RESET("Password reset successfully. You can now sign in with your new password."),
    AUTH_PASSWORD_CHANGED("Password changed successfully."),
    FILE_TOO_LARGE("The uploaded file exceeds the allowed size limit (10 MB per file)."),
    INVALID_DATA("The submitted data is invalid. Please check your input."),
    INVALID_FIELDS("Please check the submitted fields."),
    INVALID_CREDENTIALS("The email or password is incorrect."),
    ACCESS_DENIED("You are not authorized to perform this action."),
    REQUEST_FAILED("The request could not be completed."),
    INTERNAL_ERROR("An unexpected error occurred. Please try again later.");

    private final String message;

    ApiMessage(String message) { this.message = message; }

    public String getMessage() { return message; }
}
